import {Metadata} from 'next'

export const metadata = {
  title: {
    default: 'Home',
    template:"%s | Atanu"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          header
        </header>
        {children}
        <footer>
          footer
        </footer>
      </body>
    </html>
  )
}
